### ISSUE TITLE
Hello I "think" I followed all steps and i recieve when i want to open an existing VBP error ACCESS DENIED

### ISSUE THREAD

**Issue by bedeleu** [VykosX/ModernVB#1]
Hello I "think" I followed all steps and i recieve when i want to open an existing VBP error ACCESS DENIED

**Comment by bedeleu** [comment]
after a setu VB6.exe to Run as a administrator i recieve this error  
The file 'VBA6.DLL' is out of date.  This program requires a newer version.

**Comment by bedeleu** [comment]
Also on registering the dll  I recieve this error 

---------------------------
RegSvr32
---------------------------
The module "C:\Program Files (x86)\Microsoft Visual Studio\VB98\ModernVB v1.7.dll" was loaded but the call to DllRegisterServer failed with error code 0x80004005.

For more information about this problem, search online using the error code as a search term.
---------------------------
OK   
---------------------------

**Comment by jroozee** [comment]
@bedeleu  you need to run the DeltaPatcherLite.exe software as administrator
However, I also get  the error "The module "C:\Program Files (x86)\Microsoft Visual Studio\VB98\ModernVB v1.7.dll" was loaded but the call to DllRegisterServer failed with error code 0x80004005."

And when I run the oatch on VB6.EXE, it errors out "An error has occurred! See log for more information".
Log says "An error has occurred: xdelta3: target window checksum mismatch: XD3_INVALID_INPUT"

Yes VB6 is SP6

I am trying the English patch.

**Comment by FrannDzs** [comment]
@bedeleu @jroozee 
Hi

I didn't have any problems, just follow the instructions in the text file and the instructions in the program carefully. 
It describes from which SP6 installers you have to extract the mentioned files and the links to those service packs. 

They are not all the same, in my case, it asked for "vbsp6.exe" for "vb6.exe" and "vb6ide.dll" in Spanish, and to patch vba6.dll I needed the "vs6sp6b.exe" in English, where I had to extract "vba6.dll" from "vs6sp6b2.cab", and I patched it by selecting the International option. I hope it will help you.

**Comment by VykosX** [comment]
> Also on registering the dll I recieve this error
> 
> ## RegSvr32
> The module "C:\Program Files (x86)\Microsoft Visual Studio\VB98\ModernVB v1.7.dll" was loaded but the call to DllRegisterServer failed with error code 0x80004005.
> 
> ## For more information about this problem, search online using the error code as a search term.
> ## OK

If I'm not mistaken this issue with registering the DLL happens on Windows 10 and later and the solution is to first register the file MSADDNDR.DLL in C:\Windows\Syswow64 and also in C:\Program Files (x86)\Common Files\DESIGNER. Then you can attempt to register ModernVB.dll and it should succeed.
